// Pedro Casanova (casanova@ujaen.es) 2020/04-11

#ifndef SETTINGS_VALUES_H
#define SETTINGS_VALUES_H


#define DEFAULT_MAINFRAMEWIDTH 1100
#define DEFAULT_MAINFRAMEHEIGHT	800
#define DEFAULT_MAINFRAMELEFT 20
#define DEFAULT_MAINFRAMETOP 20
#define DEFAULT_TIMEPERSTEP 25
#define DEFAULT_REFRESHRATE 60
#define DEFAULT_WIRECONNRADIUS 0.15f
#define DEFAULT_GATELIBFILE "UserLib.xml"
#define DEFAULT_TEXTFONTFILE "arial.glf"
#define DEFAULT_GRIDLINEVISIBLE true
#define DEFAULT_WIRECONNVISIBLE false
#define DEFAULT_WIDEOUTLINE true
#define DEFAULT_COMPONENTCOLLVISIBLE false
#define DEFAULT_ADJUSTBITMAP false
#define DEFAULT_MARKDEPRECATED true

#endif

