// Pedro Casanova (casanova@ujaen.es) 2020/04-12

#ifndef SETTINGS_VALUES_H
#define SETTINGS_VALUES_H

#define SETTINGS_IN_REG true

#define DEFAULT_MAINFRAMEWIDTH 1100
#define DEFAULT_MAINFRAMEHEIGHT	800
#define DEFAULT_MAINFRAMELEFT 20
#define DEFAULT_MAINFRAMETOP 20
#define DEFAULT_MAINFRAMEMAXIMIZE false
#define DEFAULT_TIMEPERSTEP 25
#define DEFAULT_REFRESHRATE 60
#define DEFAULT_WIRECONNRADIUS 0.15f
#define DEFAULT_MAINLIBFILE "res"				// "cl_gatedefs.xml"
#define DEFAULT_USERLIBFILE "UserLib.xml"
#define DEFAULT_HELPFILE "KLS_Logic.chm"
#define DEFAULT_TEXTFONTFILE "res"				// "arial.glf"
#define DEFAULT_GRIDLINEVISIBLE true
#define DEFAULT_WIRECONNVISIBLE false
#define DEFAULT_WIDEOUTLINE true
#define DEFAULT_COMPONENTCOLLVISIBLE false
#define DEFAULT_ADJUSTBITMAP true
#define DEFAULT_MARKDEPRECATED true

#endif

